Add documentation
Beyley/Kettu pull request #2
Opened 2021-10-30 20:24 UTC by jvyden

2021-10-30 22:21 UTC, Beyley requested changes

2021-10-30 22:21 UTC, Beyley commented on Kettu/LoggerBase.cs
> +    /// </summary>
what

2021-10-30 22:22 UTC, Beyley commented
One more thing: you forgot to document LoggerBase.Dispose

2021-10-31 01:23 UTC, jvyden commented on Kettu/LoggerBase.cs
> +    /// </summary>
oops

2021-10-31 01:23 UTC, jvyden commented
The button should be near the top-right of the front page.

2021-10-31 01:38 UTC, Beyley approved these changes

2021-10-31 01:39 UTC, Beyley commented
tag added too btw

2021-10-31 01:39 UTC, merged